apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
  name: httpd-new
spec:
  replicas: 10
  selector:
    matchLabels:
      app: httpd
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd-new
          command: ["/bin/bash", "-c"]
          args: ["sleep 2; exit 1"]
